name: deploy the project
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint the code
        run: npm lint
      - name: Test the code
        run: npm test
      - name: Build the project
        run: npm build
      - name: Deploy
        run: echo "deploying.."
