name: deploy the project
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Log node version
        run: node -v
      - name: Install dependencies
        run: npm ci
      - name: Lint the code
        run: npm run lint
      - name: Test the code
        run: npm test
      - name: Build the project
        run: npm run build
      - name: Deploy
        run: echo "deploying.."
